#!/usr/bin/bash
# Automating run of docker hosts tests

# Assumption: Docker IPs will be the default 172.17.0.0/16, so, docker_1 will always be 172.17.0.1

# Declare variables
docker_image=my-docker-image:latest
git_repo=socket_programming_cpp
containers='docker_1'
source_code=server.cpp
compiled_binary=compiled_server


# Build and start containers
# Run tasks on docker_1 as server
echo " "
echo "============== UNITTEST SERVER RUN =================="
for value in $containers
do
   # running of docker-exec commands in the containers
   # docker exec docker_1 git clone https://github.com/254In61/socket_programming_cpp.git
   # docker exec docker_1 g++ -o socket_programming_cpp/compiled_client socket_programming_cpp/client.cpp && socket_programming_cpp/compiled_client

   echo " "
   echo "***CONTAINER NAME : $value "
   docker exec $value git clone https://github.com/254In61/$git_repo.git && echo "Git cloning of code into container successfull.."
   docker exec $value g++ -o $git_repo/$compiled_binary $git_repo/$source_code 
   docker exec $value $git_repo/$compiled_binary &
   echo " "

done
