---
# Run test on the docker containers
# When image was created. ref Dockerfile, git and python3 were installed as a layer ontop

- name: git clone https://github.com/254In61/{{ git_repo }}.git
  shell: "docker exec {{ container_common_name }}_{{ item }} git clone https://github.com/254In61/{{ git_repo }}.git"
  with_sequence: count={{ number_of_containers }}
  ignore_errors: yes
  # Using this approach to run everything under docker exec and not have to ssh on the docker containers like usual Ansible code.
  # SSH into the containers seem to take too much of time.
      
- name: Compile the .cpp code
  shell: "docker exec {{ container_common_name }}_{{ item }} g++ -o {{ compiled_binary }} {{ git_repo }}/{{ source_code }}"
  with_sequence: count={{ number_of_containers }}
  register: container_output
  ignore_errors: yes

- name: Run the compiled binary file
  shell: "docker exec {{ container_common_name }}_{{ item }} ./{{ compiled_binary }}"
  with_sequence: count={{ number_of_containers }}
  register: container_output
  ignore_errors: yes

- debug:
    var: container_output
  ignore_errors: yes

